-- AlterTable
ALTER TABLE "Guild" ADD COLUMN     "GuildLbCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "PeakGP" INTEGER,
ADD COLUMN     "PeakGPRank" INTEGER;

-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "FameLBcount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "PeakFame" INTEGER,
ADD COLUMN     "PeakFameRank" INTEGER,
ADD COLUMN     "PeakRP" INTEGER,
ADD COLUMN     "PeakRPRank" INTEGER,
ADD COLUMN     "RPLbcount" INTEGER NOT NULL DEFAULT 0;
